// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
double calculate_p_init(int sample_n);
extern "C" SEXP _vsexample_calculate_p_init(SEXP sample_n) {
  BEGIN_CPP11
    return cpp11::as_sexp(calculate_p_init(cpp11::as_cpp<cpp11::decay_t<int>>(sample_n)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_vsexample_calculate_p_init", (DL_FUNC) &_vsexample_calculate_p_init, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_vsexample(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
